package com.oscarparty.data.dao.mappers;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import static com.oscarparty.data.dao.mappers.PlayerDataObject.PLAYER_TABLE;

@DynamoDBTable(tableName = PLAYER_TABLE)
public class PlayerDataObject {

  public static final String PLAYER_TABLE = "Players";
  public static final String NAME_INDEX = "playerNameIndex";

  public static final String ID_ATTRIBUTE = "id";
  public static final String NAME_ATTRIBUTE = "playerName";

  @DynamoDBHashKey(attributeName = ID_ATTRIBUTE)
  @DynamoDBAutoGeneratedKey
  private String id;

  @DynamoDBIndexHashKey(attributeName = NAME_ATTRIBUTE, globalSecondaryIndexName = NAME_INDEX)
  private String playerName;

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public String getPlayerName() {
    return playerName;
  }

  public void setPlayerName(String playerName) {
    this.playerName = playerName;
  }
}
